# Site settings
course_name: Combinatória
course_description: "Hub para pesquisadores (e futuros pesquisadores) da combinatória brasileira"
course_semester: "2024"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://combinatoriais.github.io/" # the base hostname & protocol for your site

schoolname: "Hogwarts"
schoolurl: "https://hogwarts.edu"
twitter_username: username 

address: |
    School of Witchcraft and Wizardry
    Hogwarts
    Scotland

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
